[build-system]
requires = ["pip>=22.3.1",
            "setuptools>=66.0.0",
            "wheel>=0.38.4"]

build-backend = "setuptools.build_meta"

[project]
name = "sb_db_common"
readme = "README.md"
version = "0.0.1"
authors = [
    { name = "Stephen Booth", email = "stephen.booth.za@gmail.com" },
]
description = "A set of db wrappers"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["psycopg2 >= 2.9.9",
            "mysql-connector-python >= 8.1.0",
            "protobuf >= 4.21.1"]

